// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcEaToSTHsimwf9Mnpf2CZoFd8NF1vVZw',
    appId: '1:71337103361:web:594a704e01ec03314cf000',
    messagingSenderId: '71337103361',
    projectId: 'alarmnotificationapp-b618f',
    authDomain: 'alarmnotificationapp-b618f.firebaseapp.com',
    storageBucket: 'alarmnotificationapp-b618f.firebasestorage.app',
    measurementId: 'G-HD4PL2H4NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIkZaA71apGYHZ2O-UM0B4rmMMZl3rKkc',
    appId: '1:71337103361:android:625ab5d8528d9fd44cf000',
    messagingSenderId: '71337103361',
    projectId: 'alarmnotificationapp-b618f',
    storageBucket: 'alarmnotificationapp-b618f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_P92hE3F3kNbz3YPScakJB2-3WiipNo',
    appId: '1:71337103361:ios:382343b022687fbf4cf000',
    messagingSenderId: '71337103361',
    projectId: 'alarmnotificationapp-b618f',
    storageBucket: 'alarmnotificationapp-b618f.firebasestorage.app',
    iosBundleId: 'com.example.alarmNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_P92hE3F3kNbz3YPScakJB2-3WiipNo',
    appId: '1:71337103361:ios:382343b022687fbf4cf000',
    messagingSenderId: '71337103361',
    projectId: 'alarmnotificationapp-b618f',
    storageBucket: 'alarmnotificationapp-b618f.firebasestorage.app',
    iosBundleId: 'com.example.alarmNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcEaToSTHsimwf9Mnpf2CZoFd8NF1vVZw',
    appId: '1:71337103361:web:15d6d9ee731d5c0f4cf000',
    messagingSenderId: '71337103361',
    projectId: 'alarmnotificationapp-b618f',
    authDomain: 'alarmnotificationapp-b618f.firebaseapp.com',
    storageBucket: 'alarmnotificationapp-b618f.firebasestorage.app',
    measurementId: 'G-N0TGK67GK6',
  );
}
